from datetime import datetime
from typing import Protocol
from uuid import UUID

from fb_crawl.core.jobs import Page
from .models import BatchAck, RowFilters, SessionCreate, SessionFilters, SessionIdentity, SessionRow, SessionRowInput, SessionSummary


class InteractionSessionRepository(Protocol):
    def get_person(self, account_id: int, session_id: UUID, person_id: UUID) -> SessionIdentity: ...
    def record_result(self, account_id: int, session_id: UUID, person_id: UUID, event_id: int, state: str, now: datetime) -> None: ...
    def create(self, account_id: int, value: SessionCreate, now: datetime) -> SessionSummary: ...
    def upsert_rows(self, account_id: int, session_id: UUID, rows: tuple[SessionRowInput, ...], now: datetime) -> BatchAck: ...
    def get(self, account_id: int, session_id: UUID) -> SessionSummary | None: ...
    def transition(self, account_id: int, session_id: UUID, status: str, revision: int, now: datetime) -> SessionSummary: ...
    def delete(self, account_id: int, session_id: UUID) -> bool: ...
    def list_sessions(self, account_id: int, filters: SessionFilters, cursor: str | None, limit: int) -> Page[SessionSummary]: ...
    def list_rows(self, account_id: int, session_id: UUID, filters: RowFilters, cursor: str | None, limit: int) -> Page[SessionRow]: ...
